#pragma once

#include "FunctionNodeModel.hpp"

class PointInterpolatorModel;
class InterpolatorModel;

class Func1x1PointInterpolationModel : public Function1x1NodeModel
{ Q_OBJECT
public:
	Func1x1PointInterpolationModel();
	~Func1x1PointInterpolationModel() override;

	virtual QString caption() const override;
	virtual QString name() const override;
	virtual std::shared_ptr<Func1x1Data> function() override;
	QString description() const override
		{
		return R"(This function is generated by smoothly interpolating between a set of points in a plane, defined in a node view widget.
Double clicking the widget creates a new point.
Right clicking a point deletes it.
Left clicking and dragging an existing point moves it.
Holding shift while moving a point locks it to an integer grid.

Input - Number:
	If provided, the node will output a constant function equal to itself evaluated at the Input.
		)";
		}

	virtual QJsonObject save() const override;
	virtual void restore( const QJsonObject & p ) override;
	virtual ControllerPairs makeInputControllers() override;
	virtual QWidget * makeHeaderWidget() override;

	std::unique_ptr<PointInterpolatorModel> piModel;
};

